//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FedExShippingWCF.FedExAvailabilityValidationService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ValidationAvailabilityAndCommitmentServiceSoapBinding", Namespace="http://fedex.com/ws/vacs/v8")]
    public partial class ValidationAvailabilityAndCommitmentService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback serviceAvailabilityOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ValidationAvailabilityAndCommitmentService() {
            this.Url = global::FedExShippingWCF.Properties.Settings.Default.FedExShippingWCF_FedExAvailabilityValidationService_ValidationAvailabilityAndCommitmentService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event serviceAvailabilityCompletedEventHandler serviceAvailabilityCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fedex.com/ws/vacs/v8/serviceAvailability", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ServiceAvailabilityReply", Namespace="http://fedex.com/ws/vacs/v8")]
        public ServiceAvailabilityReply serviceAvailability([System.Xml.Serialization.XmlElementAttribute(Namespace="http://fedex.com/ws/vacs/v8")] ServiceAvailabilityRequest ServiceAvailabilityRequest) {
            object[] results = this.Invoke("serviceAvailability", new object[] {
                        ServiceAvailabilityRequest});
            return ((ServiceAvailabilityReply)(results[0]));
        }
        
        /// <remarks/>
        public void serviceAvailabilityAsync(ServiceAvailabilityRequest ServiceAvailabilityRequest) {
            this.serviceAvailabilityAsync(ServiceAvailabilityRequest, null);
        }
        
        /// <remarks/>
        public void serviceAvailabilityAsync(ServiceAvailabilityRequest ServiceAvailabilityRequest, object userState) {
            if ((this.serviceAvailabilityOperationCompleted == null)) {
                this.serviceAvailabilityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnserviceAvailabilityOperationCompleted);
            }
            this.InvokeAsync("serviceAvailability", new object[] {
                        ServiceAvailabilityRequest}, this.serviceAvailabilityOperationCompleted, userState);
        }
        
        private void OnserviceAvailabilityOperationCompleted(object arg) {
            if ((this.serviceAvailabilityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.serviceAvailabilityCompleted(this, new serviceAvailabilityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/vacs/v8")]
    public partial class ServiceAvailabilityRequest {
        
        private WebAuthenticationDetail webAuthenticationDetailField;
        
        private ClientDetail clientDetailField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        private Address originField;
        
        private Address destinationField;
        
        private System.DateTime shipDateField;
        
        private CarrierCodeType carrierCodeField;
        
        private bool carrierCodeFieldSpecified;
        
        private ServiceType serviceField;
        
        private bool serviceFieldSpecified;
        
        private PackagingType packagingField;
        
        private bool packagingFieldSpecified;
        
        /// <remarks/>
        public WebAuthenticationDetail WebAuthenticationDetail {
            get {
                return this.webAuthenticationDetailField;
            }
            set {
                this.webAuthenticationDetailField = value;
            }
        }
        
        /// <remarks/>
        public ClientDetail ClientDetail {
            get {
                return this.clientDetailField;
            }
            set {
                this.clientDetailField = value;
            }
        }
        
        /// <remarks/>
        public TransactionDetail TransactionDetail {
            get {
                return this.transactionDetailField;
            }
            set {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        public VersionId Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public Address Origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        public Address Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ShipDate {
            get {
                return this.shipDateField;
            }
            set {
                this.shipDateField = value;
            }
        }
        
        /// <remarks/>
        public CarrierCodeType CarrierCode {
            get {
                return this.carrierCodeField;
            }
            set {
                this.carrierCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CarrierCodeSpecified {
            get {
                return this.carrierCodeFieldSpecified;
            }
            set {
                this.carrierCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ServiceType Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ServiceSpecified {
            get {
                return this.serviceFieldSpecified;
            }
            set {
                this.serviceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public PackagingType Packaging {
            get {
                return this.packagingField;
            }
            set {
                this.packagingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PackagingSpecified {
            get {
                return this.packagingFieldSpecified;
            }
            set {
                this.packagingFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/vacs/v8")]
    public partial class WebAuthenticationDetail {
        
        private WebAuthenticationCredential parentCredentialField;
        
        private WebAuthenticationCredential userCredentialField;
        
        /// <remarks/>
        public WebAuthenticationCredential ParentCredential {
            get {
                return this.parentCredentialField;
            }
            set {
                this.parentCredentialField = value;
            }
        }
        
        /// <remarks/>
        public WebAuthenticationCredential UserCredential {
            get {
                return this.userCredentialField;
            }
            set {
                this.userCredentialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/vacs/v8")]
    public partial class WebAuthenticationCredential {
        
        private string keyField;
        
        private string passwordField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/vacs/v8")]
    public partial class ServiceAvailabilityOption {
        
        private ServiceType serviceField;
        
        private bool serviceFieldSpecified;
        
        private System.DateTime deliveryDateField;
        
        private bool deliveryDateFieldSpecified;
        
        private DayOfWeekType deliveryDayField;
        
        private bool deliveryDayFieldSpecified;
        
        private string destinationStationIdField;
        
        private string destinationAirportIdField;
        
        private TransitTimeType transitTimeField;
        
        private bool transitTimeFieldSpecified;
        
        /// <remarks/>
        public ServiceType Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ServiceSpecified {
            get {
                return this.serviceFieldSpecified;
            }
            set {
                this.serviceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DeliveryDate {
            get {
                return this.deliveryDateField;
            }
            set {
                this.deliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeliveryDateSpecified {
            get {
                return this.deliveryDateFieldSpecified;
            }
            set {
                this.deliveryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public DayOfWeekType DeliveryDay {
            get {
                return this.deliveryDayField;
            }
            set {
                this.deliveryDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeliveryDaySpecified {
            get {
                return this.deliveryDayFieldSpecified;
            }
            set {
                this.deliveryDayFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string DestinationStationId {
            get {
                return this.destinationStationIdField;
            }
            set {
                this.destinationStationIdField = value;
            }
        }
        
        /// <remarks/>
        public string DestinationAirportId {
            get {
                return this.destinationAirportIdField;
            }
            set {
                this.destinationAirportIdField = value;
            }
        }
        
        /// <remarks/>
        public TransitTimeType TransitTime {
            get {
                return this.transitTimeField;
            }
            set {
                this.transitTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransitTimeSpecified {
            get {
                return this.transitTimeFieldSpecified;
            }
            set {
                this.transitTimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/vacs/v8")]
    public enum ServiceType {
        
        /// <remarks/>
        EUROPE_FIRST_INTERNATIONAL_PRIORITY,
        
        /// <remarks/>
        FEDEX_1_DAY_FREIGHT,
        
        /// <remarks/>
        FEDEX_2_DAY,
        
        /// <remarks/>
        FEDEX_2_DAY_AM,
        
        /// <remarks/>
        FEDEX_2_DAY_FREIGHT,
        
        /// <remarks/>
        FEDEX_3_DAY_FREIGHT,
        
        /// <remarks/>
        FEDEX_DISTANCE_DEFERRED,
        
        /// <remarks/>
        FEDEX_EXPRESS_SAVER,
        
        /// <remarks/>
        FEDEX_FIRST_FREIGHT,
        
        /// <remarks/>
        FEDEX_GROUND,
        
        /// <remarks/>
        FEDEX_NEXT_DAY_AFTERNOON,
        
        /// <remarks/>
        FEDEX_NEXT_DAY_EARLY_MORNING,
        
        /// <remarks/>
        FEDEX_NEXT_DAY_END_OF_DAY,
        
        /// <remarks/>
        FEDEX_NEXT_DAY_FREIGHT,
        
        /// <remarks/>
        FEDEX_NEXT_DAY_MID_MORNING,
        
        /// <remarks/>
        FIRST_OVERNIGHT,
        
        /// <remarks/>
        GROUND_HOME_DELIVERY,
        
        /// <remarks/>
        INTERNATIONAL_DISTRIBUTION_FREIGHT,
        
        /// <remarks/>
        INTERNATIONAL_ECONOMY,
        
        /// <remarks/>
        INTERNATIONAL_ECONOMY_DISTRIBUTION,
        
        /// <remarks/>
        INTERNATIONAL_ECONOMY_FREIGHT,
        
        /// <remarks/>
        INTERNATIONAL_FIRST,
        
        /// <remarks/>
        INTERNATIONAL_PRIORITY,
        
        /// <remarks/>
        INTERNATIONAL_PRIORITY_DISTRIBUTION,
        
        /// <remarks/>
        INTERNATIONAL_PRIORITY_EXPRESS,
        
        /// <remarks/>
        INTERNATIONAL_PRIORITY_FREIGHT,
        
        /// <remarks/>
        PRIORITY_OVERNIGHT,
        
        /// <remarks/>
        SAME_DAY,
        
        /// <remarks/>
        SAME_DAY_CITY,
        
        /// <remarks/>
        STANDARD_OVERNIGHT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/vacs/v8")]
    public enum DayOfWeekType {
        
        /// <remarks/>
        FRI,
        
        /// <remarks/>
        MON,
        
        /// <remarks/>
        SAT,
        
        /// <remarks/>
        SUN,
        
        /// <remarks/>
        THU,
        
        /// <remarks/>
        TUE,
        
        /// <remarks/>
        WED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/vacs/v8")]
    public enum TransitTimeType {
        
        /// <remarks/>
        EIGHTEEN_DAYS,
        
        /// <remarks/>
        EIGHT_DAYS,
        
        /// <remarks/>
        ELEVEN_DAYS,
        
        /// <remarks/>
        FIFTEEN_DAYS,
        
        /// <remarks/>
        FIVE_DAYS,
        
        /// <remarks/>
        FOURTEEN_DAYS,
        
        /// <remarks/>
        FOUR_DAYS,
        
        /// <remarks/>
        NINETEEN_DAYS,
        
        /// <remarks/>
        NINE_DAYS,
        
        /// <remarks/>
        ONE_DAY,
        
        /// <remarks/>
        SEVENTEEN_DAYS,
        
        /// <remarks/>
        SEVEN_DAYS,
        
        /// <remarks/>
        SIXTEEN_DAYS,
        
        /// <remarks/>
        SIX_DAYS,
        
        /// <remarks/>
        TEN_DAYS,
        
        /// <remarks/>
        THIRTEEN_DAYS,
        
        /// <remarks/>
        THREE_DAYS,
        
        /// <remarks/>
        TWELVE_DAYS,
        
        /// <remarks/>
        TWENTY_DAYS,
        
        /// <remarks/>
        TWO_DAYS,
        
        /// <remarks/>
        UNKNOWN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/vacs/v8")]
    public partial class NotificationParameter {
        
        private string idField;
        
        private string valueField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/vacs/v8")]
    public partial class Notification {
        
        private NotificationSeverityType severityField;
        
        private string sourceField;
        
        private string codeField;
        
        private string messageField;
        
        private string localizedMessageField;
        
        private NotificationParameter[] messageParametersField;
        
        /// <remarks/>
        public NotificationSeverityType Severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string LocalizedMessage {
            get {
                return this.localizedMessageField;
            }
            set {
                this.localizedMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MessageParameters")]
        public NotificationParameter[] MessageParameters {
            get {
                return this.messageParametersField;
            }
            set {
                this.messageParametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/vacs/v8")]
    public enum NotificationSeverityType {
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        FAILURE,
        
        /// <remarks/>
        NOTE,
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        WARNING,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/vacs/v8")]
    public partial class ServiceAvailabilityReply {
        
        private NotificationSeverityType highestSeverityField;
        
        private Notification[] notificationsField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        private ServiceAvailabilityOption[] optionsField;
        
        /// <remarks/>
        public NotificationSeverityType HighestSeverity {
            get {
                return this.highestSeverityField;
            }
            set {
                this.highestSeverityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Notifications")]
        public Notification[] Notifications {
            get {
                return this.notificationsField;
            }
            set {
                this.notificationsField = value;
            }
        }
        
        /// <remarks/>
        public TransactionDetail TransactionDetail {
            get {
                return this.transactionDetailField;
            }
            set {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        public VersionId Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Options")]
        public ServiceAvailabilityOption[] Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/vacs/v8")]
    public partial class TransactionDetail {
        
        private string customerTransactionIdField;
        
        private Localization localizationField;
        
        /// <remarks/>
        public string CustomerTransactionId {
            get {
                return this.customerTransactionIdField;
            }
            set {
                this.customerTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        public Localization Localization {
            get {
                return this.localizationField;
            }
            set {
                this.localizationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/vacs/v8")]
    public partial class Localization {
        
        private string languageCodeField;
        
        private string localeCodeField;
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LocaleCode {
            get {
                return this.localeCodeField;
            }
            set {
                this.localeCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/vacs/v8")]
    public partial class VersionId {
        
        private string serviceIdField;
        
        private int majorField;
        
        private int intermediateField;
        
        private int minorField;
        
        public VersionId() {
            this.serviceIdField = "vacs";
            this.majorField = 8;
            this.intermediateField = 0;
            this.minorField = 0;
        }
        
        /// <remarks/>
        public string ServiceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
            }
        }
        
        /// <remarks/>
        public int Major {
            get {
                return this.majorField;
            }
            set {
                this.majorField = value;
            }
        }
        
        /// <remarks/>
        public int Intermediate {
            get {
                return this.intermediateField;
            }
            set {
                this.intermediateField = value;
            }
        }
        
        /// <remarks/>
        public int Minor {
            get {
                return this.minorField;
            }
            set {
                this.minorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/vacs/v8")]
    public partial class Address {
        
        private string postalCodeField;
        
        private string countryCodeField;
        
        private string geographicCoordinatesField;
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string GeographicCoordinates {
            get {
                return this.geographicCoordinatesField;
            }
            set {
                this.geographicCoordinatesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/vacs/v8")]
    public partial class ClientDetail {
        
        private string accountNumberField;
        
        private string meterNumberField;
        
        private Localization localizationField;
        
        /// <remarks/>
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string MeterNumber {
            get {
                return this.meterNumberField;
            }
            set {
                this.meterNumberField = value;
            }
        }
        
        /// <remarks/>
        public Localization Localization {
            get {
                return this.localizationField;
            }
            set {
                this.localizationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/vacs/v8")]
    public enum CarrierCodeType {
        
        /// <remarks/>
        FDXE,
        
        /// <remarks/>
        FDXG,
        
        /// <remarks/>
        FXSP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/vacs/v8")]
    public enum PackagingType {
        
        /// <remarks/>
        FEDEX_10KG_BOX,
        
        /// <remarks/>
        FEDEX_25KG_BOX,
        
        /// <remarks/>
        FEDEX_BOX,
        
        /// <remarks/>
        FEDEX_ENVELOPE,
        
        /// <remarks/>
        FEDEX_EXTRA_LARGE_BOX,
        
        /// <remarks/>
        FEDEX_LARGE_BOX,
        
        /// <remarks/>
        FEDEX_MEDIUM_BOX,
        
        /// <remarks/>
        FEDEX_PAK,
        
        /// <remarks/>
        FEDEX_SMALL_BOX,
        
        /// <remarks/>
        FEDEX_TUBE,
        
        /// <remarks/>
        YOUR_PACKAGING,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void serviceAvailabilityCompletedEventHandler(object sender, serviceAvailabilityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class serviceAvailabilityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal serviceAvailabilityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceAvailabilityReply Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceAvailabilityReply)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591