//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FedExShippingWCF.FedExAddressValidationService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AddressValidationServiceSoapBinding", Namespace="http://fedex.com/ws/addressvalidation/v4")]
    public partial class AddressValidationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback addressValidationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AddressValidationService() {
            this.Url = global::FedExShippingWCF.Properties.Settings.Default.FedExShippingWCF_FedExAddressValidationService_AddressValidationService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event addressValidationCompletedEventHandler addressValidationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://fedex.com/ws/addressvalidation/v4/addressValidation", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("AddressValidationReply", Namespace="http://fedex.com/ws/addressvalidation/v4")]
        public AddressValidationReply addressValidation([System.Xml.Serialization.XmlElementAttribute(Namespace="http://fedex.com/ws/addressvalidation/v4")] AddressValidationRequest AddressValidationRequest) {
            object[] results = this.Invoke("addressValidation", new object[] {
                        AddressValidationRequest});
            return ((AddressValidationReply)(results[0]));
        }
        
        /// <remarks/>
        public void addressValidationAsync(AddressValidationRequest AddressValidationRequest) {
            this.addressValidationAsync(AddressValidationRequest, null);
        }
        
        /// <remarks/>
        public void addressValidationAsync(AddressValidationRequest AddressValidationRequest, object userState) {
            if ((this.addressValidationOperationCompleted == null)) {
                this.addressValidationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddressValidationOperationCompleted);
            }
            this.InvokeAsync("addressValidation", new object[] {
                        AddressValidationRequest}, this.addressValidationOperationCompleted, userState);
        }
        
        private void OnaddressValidationOperationCompleted(object arg) {
            if ((this.addressValidationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addressValidationCompleted(this, new addressValidationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/addressvalidation/v4")]
    public partial class AddressValidationRequest {
        
        private WebAuthenticationDetail webAuthenticationDetailField;
        
        private ClientDetail clientDetailField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        private System.DateTime inEffectAsOfTimestampField;
        
        private bool inEffectAsOfTimestampFieldSpecified;
        
        private AddressToValidate[] addressesToValidateField;
        
        /// <remarks/>
        public WebAuthenticationDetail WebAuthenticationDetail {
            get {
                return this.webAuthenticationDetailField;
            }
            set {
                this.webAuthenticationDetailField = value;
            }
        }
        
        /// <remarks/>
        public ClientDetail ClientDetail {
            get {
                return this.clientDetailField;
            }
            set {
                this.clientDetailField = value;
            }
        }
        
        /// <remarks/>
        public TransactionDetail TransactionDetail {
            get {
                return this.transactionDetailField;
            }
            set {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        public VersionId Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime InEffectAsOfTimestamp {
            get {
                return this.inEffectAsOfTimestampField;
            }
            set {
                this.inEffectAsOfTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InEffectAsOfTimestampSpecified {
            get {
                return this.inEffectAsOfTimestampFieldSpecified;
            }
            set {
                this.inEffectAsOfTimestampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddressesToValidate")]
        public AddressToValidate[] AddressesToValidate {
            get {
                return this.addressesToValidateField;
            }
            set {
                this.addressesToValidateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/addressvalidation/v4")]
    public partial class WebAuthenticationDetail {
        
        private WebAuthenticationCredential parentCredentialField;
        
        private WebAuthenticationCredential userCredentialField;
        
        /// <remarks/>
        public WebAuthenticationCredential ParentCredential {
            get {
                return this.parentCredentialField;
            }
            set {
                this.parentCredentialField = value;
            }
        }
        
        /// <remarks/>
        public WebAuthenticationCredential UserCredential {
            get {
                return this.userCredentialField;
            }
            set {
                this.userCredentialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/addressvalidation/v4")]
    public partial class WebAuthenticationCredential {
        
        private string keyField;
        
        private string passwordField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/addressvalidation/v4")]
    public partial class AddressAttribute {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/addressvalidation/v4")]
    public partial class ParsedPostalCodeDetail {
        
        private string baseField;
        
        private string addOnField;
        
        private string deliveryPointField;
        
        /// <remarks/>
        public string Base {
            get {
                return this.baseField;
            }
            set {
                this.baseField = value;
            }
        }
        
        /// <remarks/>
        public string AddOn {
            get {
                return this.addOnField;
            }
            set {
                this.addOnField = value;
            }
        }
        
        /// <remarks/>
        public string DeliveryPoint {
            get {
                return this.deliveryPointField;
            }
            set {
                this.deliveryPointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/addressvalidation/v4")]
    public partial class ParsedStreetLineDetail {
        
        private string houseNumberField;
        
        private string preStreetTypeField;
        
        private string leadingDirectionalField;
        
        private string streetNameField;
        
        private string streetSuffixField;
        
        private string trailingDirectionalField;
        
        private string unitLabelField;
        
        private string unitNumberField;
        
        private string ruralRouteField;
        
        private string pOBoxField;
        
        private string buildingField;
        
        private string organizationField;
        
        /// <remarks/>
        public string HouseNumber {
            get {
                return this.houseNumberField;
            }
            set {
                this.houseNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PreStreetType {
            get {
                return this.preStreetTypeField;
            }
            set {
                this.preStreetTypeField = value;
            }
        }
        
        /// <remarks/>
        public string LeadingDirectional {
            get {
                return this.leadingDirectionalField;
            }
            set {
                this.leadingDirectionalField = value;
            }
        }
        
        /// <remarks/>
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
            }
        }
        
        /// <remarks/>
        public string StreetSuffix {
            get {
                return this.streetSuffixField;
            }
            set {
                this.streetSuffixField = value;
            }
        }
        
        /// <remarks/>
        public string TrailingDirectional {
            get {
                return this.trailingDirectionalField;
            }
            set {
                this.trailingDirectionalField = value;
            }
        }
        
        /// <remarks/>
        public string UnitLabel {
            get {
                return this.unitLabelField;
            }
            set {
                this.unitLabelField = value;
            }
        }
        
        /// <remarks/>
        public string UnitNumber {
            get {
                return this.unitNumberField;
            }
            set {
                this.unitNumberField = value;
            }
        }
        
        /// <remarks/>
        public string RuralRoute {
            get {
                return this.ruralRouteField;
            }
            set {
                this.ruralRouteField = value;
            }
        }
        
        /// <remarks/>
        public string POBox {
            get {
                return this.pOBoxField;
            }
            set {
                this.pOBoxField = value;
            }
        }
        
        /// <remarks/>
        public string Building {
            get {
                return this.buildingField;
            }
            set {
                this.buildingField = value;
            }
        }
        
        /// <remarks/>
        public string Organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/addressvalidation/v4")]
    public partial class ParsedAddressPartsDetail {
        
        private ParsedStreetLineDetail parsedStreetLineField;
        
        private ParsedPostalCodeDetail parsedPostalCodeField;
        
        /// <remarks/>
        public ParsedStreetLineDetail ParsedStreetLine {
            get {
                return this.parsedStreetLineField;
            }
            set {
                this.parsedStreetLineField = value;
            }
        }
        
        /// <remarks/>
        public ParsedPostalCodeDetail ParsedPostalCode {
            get {
                return this.parsedPostalCodeField;
            }
            set {
                this.parsedPostalCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/addressvalidation/v4")]
    public partial class AddressValidationResult {
        
        private string clientReferenceIdField;
        
        private OperationalAddressStateType stateField;
        
        private bool stateFieldSpecified;
        
        private FedExAddressClassificationType classificationField;
        
        private bool classificationFieldSpecified;
        
        private Contact effectiveContactField;
        
        private Address effectiveAddressField;
        
        private ParsedAddressPartsDetail parsedAddressPartsDetailField;
        
        private AddressAttribute[] attributesField;
        
        /// <remarks/>
        public string ClientReferenceId {
            get {
                return this.clientReferenceIdField;
            }
            set {
                this.clientReferenceIdField = value;
            }
        }
        
        /// <remarks/>
        public OperationalAddressStateType State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StateSpecified {
            get {
                return this.stateFieldSpecified;
            }
            set {
                this.stateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FedExAddressClassificationType Classification {
            get {
                return this.classificationField;
            }
            set {
                this.classificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClassificationSpecified {
            get {
                return this.classificationFieldSpecified;
            }
            set {
                this.classificationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Contact EffectiveContact {
            get {
                return this.effectiveContactField;
            }
            set {
                this.effectiveContactField = value;
            }
        }
        
        /// <remarks/>
        public Address EffectiveAddress {
            get {
                return this.effectiveAddressField;
            }
            set {
                this.effectiveAddressField = value;
            }
        }
        
        /// <remarks/>
        public ParsedAddressPartsDetail ParsedAddressPartsDetail {
            get {
                return this.parsedAddressPartsDetailField;
            }
            set {
                this.parsedAddressPartsDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attributes")]
        public AddressAttribute[] Attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/addressvalidation/v4")]
    public enum OperationalAddressStateType {
        
        /// <remarks/>
        NORMALIZED,
        
        /// <remarks/>
        RAW,
        
        /// <remarks/>
        STANDARDIZED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/addressvalidation/v4")]
    public enum FedExAddressClassificationType {
        
        /// <remarks/>
        BUSINESS,
        
        /// <remarks/>
        MIXED,
        
        /// <remarks/>
        RESIDENTIAL,
        
        /// <remarks/>
        UNKNOWN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/addressvalidation/v4")]
    public partial class Contact {
        
        private string contactIdField;
        
        private string personNameField;
        
        private string titleField;
        
        private string companyNameField;
        
        private string phoneNumberField;
        
        private string phoneExtensionField;
        
        private string tollFreePhoneNumberField;
        
        private string pagerNumberField;
        
        private string faxNumberField;
        
        private string eMailAddressField;
        
        /// <remarks/>
        public string ContactId {
            get {
                return this.contactIdField;
            }
            set {
                this.contactIdField = value;
            }
        }
        
        /// <remarks/>
        public string PersonName {
            get {
                return this.personNameField;
            }
            set {
                this.personNameField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneExtension {
            get {
                return this.phoneExtensionField;
            }
            set {
                this.phoneExtensionField = value;
            }
        }
        
        /// <remarks/>
        public string TollFreePhoneNumber {
            get {
                return this.tollFreePhoneNumberField;
            }
            set {
                this.tollFreePhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PagerNumber {
            get {
                return this.pagerNumberField;
            }
            set {
                this.pagerNumberField = value;
            }
        }
        
        /// <remarks/>
        public string FaxNumber {
            get {
                return this.faxNumberField;
            }
            set {
                this.faxNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EMailAddress {
            get {
                return this.eMailAddressField;
            }
            set {
                this.eMailAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/addressvalidation/v4")]
    public partial class Address {
        
        private string[] streetLinesField;
        
        private string cityField;
        
        private string stateOrProvinceCodeField;
        
        private string postalCodeField;
        
        private string urbanizationCodeField;
        
        private string countryCodeField;
        
        private string countryNameField;
        
        private bool residentialField;
        
        private bool residentialFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StreetLines")]
        public string[] StreetLines {
            get {
                return this.streetLinesField;
            }
            set {
                this.streetLinesField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string StateOrProvinceCode {
            get {
                return this.stateOrProvinceCodeField;
            }
            set {
                this.stateOrProvinceCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UrbanizationCode {
            get {
                return this.urbanizationCodeField;
            }
            set {
                this.urbanizationCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
            }
        }
        
        /// <remarks/>
        public bool Residential {
            get {
                return this.residentialField;
            }
            set {
                this.residentialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResidentialSpecified {
            get {
                return this.residentialFieldSpecified;
            }
            set {
                this.residentialFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/addressvalidation/v4")]
    public partial class NotificationParameter {
        
        private string idField;
        
        private string valueField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/addressvalidation/v4")]
    public partial class Notification {
        
        private NotificationSeverityType severityField;
        
        private bool severityFieldSpecified;
        
        private string sourceField;
        
        private string codeField;
        
        private string messageField;
        
        private string localizedMessageField;
        
        private NotificationParameter[] messageParametersField;
        
        /// <remarks/>
        public NotificationSeverityType Severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SeveritySpecified {
            get {
                return this.severityFieldSpecified;
            }
            set {
                this.severityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string LocalizedMessage {
            get {
                return this.localizedMessageField;
            }
            set {
                this.localizedMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MessageParameters")]
        public NotificationParameter[] MessageParameters {
            get {
                return this.messageParametersField;
            }
            set {
                this.messageParametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/addressvalidation/v4")]
    public enum NotificationSeverityType {
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        FAILURE,
        
        /// <remarks/>
        NOTE,
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        WARNING,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/addressvalidation/v4")]
    public partial class AddressValidationReply {
        
        private NotificationSeverityType highestSeverityField;
        
        private Notification[] notificationsField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        private System.DateTime replyTimestampField;
        
        private bool replyTimestampFieldSpecified;
        
        private AddressValidationResult[] addressResultsField;
        
        /// <remarks/>
        public NotificationSeverityType HighestSeverity {
            get {
                return this.highestSeverityField;
            }
            set {
                this.highestSeverityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Notifications")]
        public Notification[] Notifications {
            get {
                return this.notificationsField;
            }
            set {
                this.notificationsField = value;
            }
        }
        
        /// <remarks/>
        public TransactionDetail TransactionDetail {
            get {
                return this.transactionDetailField;
            }
            set {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        public VersionId Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReplyTimestamp {
            get {
                return this.replyTimestampField;
            }
            set {
                this.replyTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReplyTimestampSpecified {
            get {
                return this.replyTimestampFieldSpecified;
            }
            set {
                this.replyTimestampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddressResults")]
        public AddressValidationResult[] AddressResults {
            get {
                return this.addressResultsField;
            }
            set {
                this.addressResultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/addressvalidation/v4")]
    public partial class TransactionDetail {
        
        private string customerTransactionIdField;
        
        private Localization localizationField;
        
        /// <remarks/>
        public string CustomerTransactionId {
            get {
                return this.customerTransactionIdField;
            }
            set {
                this.customerTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        public Localization Localization {
            get {
                return this.localizationField;
            }
            set {
                this.localizationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/addressvalidation/v4")]
    public partial class Localization {
        
        private string languageCodeField;
        
        private string localeCodeField;
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LocaleCode {
            get {
                return this.localeCodeField;
            }
            set {
                this.localeCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/addressvalidation/v4")]
    public partial class VersionId {
        
        private string serviceIdField;
        
        private int majorField;
        
        private int intermediateField;
        
        private int minorField;
        
        public VersionId() {
            this.serviceIdField = "aval";
            this.majorField = 4;
            this.intermediateField = 0;
            this.minorField = 0;
        }
        
        /// <remarks/>
        public string ServiceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
            }
        }
        
        /// <remarks/>
        public int Major {
            get {
                return this.majorField;
            }
            set {
                this.majorField = value;
            }
        }
        
        /// <remarks/>
        public int Intermediate {
            get {
                return this.intermediateField;
            }
            set {
                this.intermediateField = value;
            }
        }
        
        /// <remarks/>
        public int Minor {
            get {
                return this.minorField;
            }
            set {
                this.minorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/addressvalidation/v4")]
    public partial class AddressToValidate {
        
        private string clientReferenceIdField;
        
        private Contact contactField;
        
        private Address addressField;
        
        /// <remarks/>
        public string ClientReferenceId {
            get {
                return this.clientReferenceIdField;
            }
            set {
                this.clientReferenceIdField = value;
            }
        }
        
        /// <remarks/>
        public Contact Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/addressvalidation/v4")]
    public partial class ClientDetail {
        
        private string accountNumberField;
        
        private string meterNumberField;
        
        private string integratorIdField;
        
        private Localization localizationField;
        
        /// <remarks/>
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string MeterNumber {
            get {
                return this.meterNumberField;
            }
            set {
                this.meterNumberField = value;
            }
        }
        
        /// <remarks/>
        public string IntegratorId {
            get {
                return this.integratorIdField;
            }
            set {
                this.integratorIdField = value;
            }
        }
        
        /// <remarks/>
        public Localization Localization {
            get {
                return this.localizationField;
            }
            set {
                this.localizationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void addressValidationCompletedEventHandler(object sender, addressValidationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addressValidationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addressValidationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddressValidationReply Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddressValidationReply)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591